### ISSUE TITLE
Building on other regions

### ISSUE THREAD

**Issue by gsdevme** [irvingpop/packer-chef-highperf-centos-ami#1]
Hi, 

What exactly is the source of this? for example trying to build on other regions fails. I can't see to locate this, would be helpful If I knew what this image was. 

CentOS seems to have really poor support in terms of a nice barebones image and this one looks really gone minus a few bits Id remove if I could build it. 

Cheers.

```
      "source_ami": "ami-cb1ec7b3",
```

**Comment by gsdevme** [comment]
![screen shot 2018-02-13 at 17 25 03](https://user-images.githubusercontent.com/319498/36163970-db970adc-10e2-11e8-8a28-572399cbf9f5.png)

Hi sorry solved my own issue, thanks though 👍

**Comment by irvingpop** [comment]
Howdy @gsdevme !   Building the base image is a bit of a manual process performed by this script:  https://github.com/irvingpop/packer-chef-highperf-centos7-ami/blob/master/create_base_ami.sh

Please let me know if you have any questions, contributions or feedback!
