### ISSUE TITLE
AMI for South America (São Paulo)

### ISSUE THREAD

**Issue by jsooter** [irvingpop/packer-chef-highperf-centos-ami#4]
There is no image for the South America (São Paulo) region. Would you please create one?

**Comment by irvingpop** [comment]
sure @jsooter !   I may not get back to this immediately, but I could get there sooner if you could send me a PR!

**Comment by jsooter** [comment]
Hi @irvingpop do I just add the region to "ami_regions"in packer.json? If that's all I gotta do I'm happy to do a PR.

**Comment by irvingpop** [comment]
Yep, that's it!

**Comment by jsooter** [comment]
Thanks for adding that! I see the new AMI on AWS so I'm closing this.
