### ISSUE TITLE
Praise really, no bugs

### ISSUE THREAD

**Issue by siebrand** [irvingpop/packer-chef-highperf-centos-ami#6]
Thanks for making this available. I've played around with this in the repo https://github.com/siebrand/packer-chef-highperf-centos7-ami/ and I've made some improvements and additions that I would like to give back if you're interested.

Could you please have a look and let me know which areas of the updates you'd like me to create pull requests for?

- modularity in packer.json provisioners (I split up install_prereqs.sh in a bunch of topical scripts that I think will be much easier to maintain and contribute to, as well as just update packer.json in a clone to remove a few unwanted modules and one is off)
- updates and documentation in create_base_ami.sh
- added modules (ssm, puppet, ...)
- added packages in sysadmin tools: bzip2 nfs-utils nmap screen tmpwatch tree zip htop tcping

**Comment by irvingpop** [comment]
This is awesome, @siebrand !!!     I'd love to take all of these changes.   Couple of things would make this easy to merge:
- in the `packer.json`,  the `ami_regions` could be turned into a variable for easier customization: https://www.packer.io/docs/templates/user-variables.html#using-array-values
- for example purposes, should we put chef, docker, puppet and ssm-agent all in the array and let users remove things?   
- The README could be generalized to mention all the CM tools, I think.  
- If you're interested, I'd love to add you as a collaborator to the project and set up a CODEOWNERs file

Thank you so much for reaching out!

**Comment by siebrand** [comment]
I'll give things a read. Time to go and sleep now. Not sure when I have time again to work on this. I've spent about a 6-7 hours on this now, and I think it's really neat. I have 4 clients that I do AWS work for, mostly with CentOS images, and I think we can do so much better than CentOS currently does -- and shave minutes of deployments deployments on top of it. I know that's one of your primary goals.
I'll hopefully be trying out the images in some test environments soon, so I can battle test them, instead of watching in awe how AMI IDs pop up in my EC2 Dashboard ;).
If I can manage to find the time, I'd absolutely prefer to contribute to a single repo, instead of having to maintain my own fork and keep close eye on what's happening upstream.
TTYL!

**Comment by irvingpop** [comment]
hi @siebrand I hope you've been well!   As part of some other work, I started pulling in your changes to this repo.  Please let me know the best way to credit you for those, because they are excellent work!

I also thought you'd be excited to see the new "base AMI" build process I've created using Packer's "EBS Surrogate" mode.  This takes all the manual work out of the process, and should hopefully make it easy for new users to adopt.   

Code here:  https://github.com/irvingpop/packer-chef-highperf-centos7-ami/tree/marketplace/create_base_ami

Thank you again for your collaboration!

**Comment by siebrand** [comment]
Great that you are doing this yourself. Sorry for not finding the time to get this done myself.

That EBS surrogate mode sounds great. I'll make sure to validate the process, and provide feedback.

I had prepared a patch for the base AMI locally a while ago, but then I got distracted again by real life. I think I just made too many changes to easily submit them for you to review and merge. Next time I'll simply create a branch immediately and will try to submit them as pull requests as soon as I find a particular change working or "being better" than what was there before.

I'm not in the game for fame, so if there is a contributors list, adding "Siebrand Mazeland <siebrand@kitano.nl>" there somewhere will suffice. I agree to any license that the current code has, as well as future license changes.

Cheers!

**Comment by irvingpop** [comment]
hey @siebrand could I please get a second pair of eyes from you on this issue?  https://github.com/irvingpop/packer-chef-highperf-centos7-ami/commit/b9628eda8c2ac4041458dea18c26400a19233d30

If you have IPv6 enabled in your VPC, it seems that cloud-init hard codes some settings that only work with NetworkManager present.

**Comment by siebrand** [comment]
> If you have IPv6 enabled in your VPC

I'm not using IPv6 in VPC, so I really have no idea, unfortunately. Maybe open a new issue, with a descriptive summary, hoping that someone will come along who knows their stuff relating to this issue?

**Comment by irvingpop** [comment]
no problem, the IPv6 workaround has been in place long enough that everyone is used to it, nobody seems to complain :) 
tracking here:  https://bugs.launchpad.net/cloud-init/+bug/1808647
